CREATE TABLE IF NOT EXISTS sys_user (
    user_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(64) NOT NULL,
    password VARCHAR(255) NOT NULL,
    salt VARCHAR(255) NULL,
    real_name VARCHAR(128) NULL,
    id_card_number VARCHAR(32) NULL,
    gender VARCHAR(32) NULL,
    contact_number VARCHAR(64) NULL,
    email VARCHAR(128) NULL,
    department VARCHAR(128) NULL,
    position VARCHAR(128) NULL,
    employee_number VARCHAR(64) NULL,
    status VARCHAR(32) NULL,
    account_expiry_date DATE NULL,
    login_failures INT NULL,
    last_login_time DATETIME(6) NULL,
    last_login_ip VARCHAR(64) NULL,
    password_update_time DATETIME(6) NULL,
    created_at DATETIME(6) NULL,
    updated_at DATETIME(6) NULL,
    created_by VARCHAR(128) NULL,
    updated_by VARCHAR(128) NULL,
    deleted_at DATETIME(6) NULL,
    remarks VARCHAR(255) NULL,
    UNIQUE KEY uk_sys_user_username (username),
    UNIQUE KEY uk_sys_user_employee_number (employee_number),
    KEY idx_sys_user_status (status),
    KEY idx_sys_user_department (department),
    KEY idx_sys_user_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sys_role (
    role_id INT PRIMARY KEY AUTO_INCREMENT,
    role_code VARCHAR(64) NOT NULL,
    role_name VARCHAR(128) NOT NULL,
    role_type VARCHAR(32) NULL,
    role_description VARCHAR(255) NULL,
    data_scope VARCHAR(64) NULL,
    status VARCHAR(32) NULL,
    sort_order INT NULL,
    created_at DATETIME(6) NULL,
    updated_at DATETIME(6) NULL,
    created_by VARCHAR(128) NULL,
    updated_by VARCHAR(128) NULL,
    deleted_at DATETIME(6) NULL,
    remarks VARCHAR(255) NULL,
    UNIQUE KEY uk_sys_role_role_code (role_code),
    KEY idx_sys_role_status (status),
    KEY idx_sys_role_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sys_permission (
    permission_id INT PRIMARY KEY AUTO_INCREMENT,
    parent_id INT NULL,
    permission_code VARCHAR(128) NOT NULL,
    permission_name VARCHAR(128) NOT NULL,
    permission_type VARCHAR(32) NULL,
    permission_description VARCHAR(255) NULL,
    menu_path VARCHAR(255) NULL,
    menu_icon VARCHAR(255) NULL,
    component VARCHAR(255) NULL,
    api_path VARCHAR(255) NULL,
    api_method VARCHAR(16) NULL,
    is_visible BOOLEAN NULL,
    is_external BOOLEAN NULL,
    sort_order INT NULL,
    status VARCHAR(32) NULL,
    created_at DATETIME(6) NULL,
    updated_at DATETIME(6) NULL,
    created_by VARCHAR(128) NULL,
    updated_by VARCHAR(128) NULL,
    deleted_at DATETIME(6) NULL,
    remarks VARCHAR(255) NULL,
    UNIQUE KEY uk_sys_permission_code (permission_code),
    KEY idx_sys_permission_parent_id (parent_id),
    KEY idx_sys_permission_status (status),
    KEY idx_sys_permission_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sys_user_role (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    role_id INT NOT NULL,
    created_at DATETIME(6) NULL,
    created_by VARCHAR(128) NULL,
    deleted_at DATETIME(6) NULL,
    KEY idx_sys_user_role_user_id (user_id),
    KEY idx_sys_user_role_role_id (role_id),
    KEY idx_sys_user_role_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sys_role_permission (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    role_id INT NOT NULL,
    permission_id INT NOT NULL,
    created_at DATETIME(6) NULL,
    created_by VARCHAR(128) NULL,
    deleted_at DATETIME(6) NULL,
    KEY idx_sys_role_permission_role_id (role_id),
    KEY idx_sys_role_permission_permission_id (permission_id),
    KEY idx_sys_role_permission_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sys_settings (
    setting_id INT PRIMARY KEY AUTO_INCREMENT,
    setting_key VARCHAR(128) NOT NULL,
    setting_value TEXT NOT NULL,
    setting_type VARCHAR(32) NULL,
    category VARCHAR(64) NULL,
    description VARCHAR(255) NULL,
    is_encrypted BOOLEAN NULL,
    is_editable BOOLEAN NULL,
    sort_order INT NULL,
    created_at DATETIME(6) NULL,
    updated_at DATETIME(6) NULL,
    updated_by VARCHAR(128) NULL,
    deleted_at DATETIME(6) NULL,
    remarks VARCHAR(255) NULL,
    UNIQUE KEY uk_sys_settings_key (setting_key),
    KEY idx_sys_settings_category (category),
    KEY idx_sys_settings_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sys_dict (
    dict_id INT PRIMARY KEY AUTO_INCREMENT,
    parent_id INT NULL,
    dict_type VARCHAR(64) NOT NULL,
    dict_code VARCHAR(64) NOT NULL,
    dict_label VARCHAR(128) NULL,
    dict_value VARCHAR(255) NULL,
    dict_description VARCHAR(255) NULL,
    css_class VARCHAR(128) NULL,
    list_class VARCHAR(128) NULL,
    is_default BOOLEAN NULL,
    is_fixed BOOLEAN NULL,
    status VARCHAR(32) NULL,
    sort_order INT NULL,
    created_at DATETIME(6) NULL,
    updated_at DATETIME(6) NULL,
    created_by VARCHAR(128) NULL,
    updated_by VARCHAR(128) NULL,
    deleted_at DATETIME(6) NULL,
    remarks VARCHAR(255) NULL,
    UNIQUE KEY uk_sys_dict_type_code (dict_type, dict_code),
    KEY idx_sys_dict_parent_id (parent_id),
    KEY idx_sys_dict_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sys_request_history (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    idempotency_key VARCHAR(128) NOT NULL,
    request_method VARCHAR(16) NULL,
    request_url VARCHAR(255) NULL,
    request_params VARCHAR(500) NULL,
    business_type VARCHAR(128) NULL,
    business_id BIGINT NULL,
    business_status VARCHAR(32) NULL,
    user_id BIGINT NULL,
    request_ip VARCHAR(64) NULL,
    created_at DATETIME(6) NULL,
    updated_at DATETIME(6) NULL,
    deleted_at DATETIME(6) NULL,
    UNIQUE KEY uk_sys_request_history_idempotency_key (idempotency_key),
    KEY idx_sys_request_history_business_type (business_type),
    KEY idx_sys_request_history_business_status (business_status),
    KEY idx_sys_request_history_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sys_backup_restore (
    backup_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    backup_type VARCHAR(32) NULL,
    backup_file_name VARCHAR(255) NULL,
    backup_file_path VARCHAR(512) NULL,
    backup_file_size BIGINT NULL,
    backup_time DATETIME(6) NULL,
    backup_duration INT NULL,
    backup_handler VARCHAR(128) NULL,
    restore_time DATETIME(6) NULL,
    restore_duration INT NULL,
    restore_status VARCHAR(32) NULL,
    restore_handler VARCHAR(128) NULL,
    error_message VARCHAR(500) NULL,
    status VARCHAR(32) NULL,
    created_at DATETIME(6) NULL,
    updated_at DATETIME(6) NULL,
    deleted_at DATETIME(6) NULL,
    remarks VARCHAR(255) NULL,
    KEY idx_sys_backup_restore_status (status),
    KEY idx_sys_backup_restore_restore_status (restore_status),
    KEY idx_sys_backup_restore_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS audit_login_log (
    log_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(64) NULL,
    login_time DATETIME(6) NULL,
    logout_time DATETIME(6) NULL,
    login_result VARCHAR(32) NULL,
    failure_reason VARCHAR(255) NULL,
    login_ip VARCHAR(64) NULL,
    login_location VARCHAR(128) NULL,
    browser_type VARCHAR(64) NULL,
    browser_version VARCHAR(64) NULL,
    os_type VARCHAR(64) NULL,
    os_version VARCHAR(64) NULL,
    device_type VARCHAR(64) NULL,
    user_agent VARCHAR(512) NULL,
    session_id VARCHAR(128) NULL,
    token VARCHAR(1024) NULL,
    created_at DATETIME(6) NULL,
    deleted_at DATETIME(6) NULL,
    remarks VARCHAR(255) NULL,
    KEY idx_audit_login_log_username (username),
    KEY idx_audit_login_log_login_result (login_result),
    KEY idx_audit_login_log_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS audit_operation_log (
    log_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    operation_type VARCHAR(32) NULL,
    operation_module VARCHAR(64) NULL,
    operation_function VARCHAR(128) NULL,
    operation_content TEXT NULL,
    operation_time DATETIME(6) NULL,
    user_id BIGINT NULL,
    username VARCHAR(64) NULL,
    real_name VARCHAR(128) NULL,
    request_method VARCHAR(16) NULL,
    request_url VARCHAR(255) NULL,
    request_params TEXT NULL,
    request_ip VARCHAR(64) NULL,
    operation_result VARCHAR(32) NULL,
    response_data LONGTEXT NULL,
    error_message VARCHAR(500) NULL,
    execution_time INT NULL,
    old_value LONGTEXT NULL,
    new_value LONGTEXT NULL,
    created_at DATETIME(6) NULL,
    deleted_at DATETIME(6) NULL,
    remarks VARCHAR(255) NULL,
    KEY idx_audit_operation_log_user_id (user_id),
    KEY idx_audit_operation_log_operation_module (operation_module),
    KEY idx_audit_operation_log_operation_result (operation_result),
    KEY idx_audit_operation_log_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
