CREATE TABLE IF NOT EXISTS driver_information (
    driver_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(128) NULL,
    id_card_number VARCHAR(32) NULL,
    gender VARCHAR(32) NULL,
    birthdate DATE NULL,
    contact_number VARCHAR(64) NULL,
    email VARCHAR(128) NULL,
    address VARCHAR(255) NULL,
    driver_license_number VARCHAR(64) NULL,
    license_type VARCHAR(32) NULL,
    first_license_date DATE NULL,
    issue_date DATE NULL,
    expiry_date DATE NULL,
    issuing_authority VARCHAR(128) NULL,
    current_points INT NULL,
    total_deducted_points INT NULL,
    status VARCHAR(32) NULL,
    created_at DATETIME(6) NULL,
    updated_at DATETIME(6) NULL,
    created_by VARCHAR(128) NULL,
    updated_by VARCHAR(128) NULL,
    deleted_at DATETIME(6) NULL,
    remarks VARCHAR(255) NULL,
    UNIQUE KEY uk_driver_information_license_number (driver_license_number),
    UNIQUE KEY uk_driver_information_id_card_number (id_card_number),
    KEY idx_driver_information_status (status),
    KEY idx_driver_information_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vehicle_information (
    vehicle_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    license_plate VARCHAR(32) NULL,
    plate_color VARCHAR(32) NULL,
    vehicle_type VARCHAR(64) NULL,
    brand VARCHAR(64) NULL,
    model VARCHAR(64) NULL,
    vehicle_color VARCHAR(32) NULL,
    engine_number VARCHAR(64) NULL,
    frame_number VARCHAR(64) NULL,
    owner_name VARCHAR(128) NULL,
    owner_id_card VARCHAR(32) NULL,
    owner_contact VARCHAR(64) NULL,
    owner_address VARCHAR(255) NULL,
    first_registration_date DATE NULL,
    registration_date DATE NULL,
    issuing_authority VARCHAR(128) NULL,
    status VARCHAR(32) NULL,
    inspection_expiry_date DATE NULL,
    insurance_expiry_date DATE NULL,
    created_at DATETIME(6) NULL,
    updated_at DATETIME(6) NULL,
    created_by VARCHAR(128) NULL,
    updated_by VARCHAR(128) NULL,
    deleted_at DATETIME(6) NULL,
    remarks VARCHAR(255) NULL,
    UNIQUE KEY uk_vehicle_information_license_plate (license_plate),
    UNIQUE KEY uk_vehicle_information_frame_number (frame_number),
    KEY idx_vehicle_information_status (status),
    KEY idx_vehicle_information_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS driver_vehicle (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    driver_id BIGINT NOT NULL,
    vehicle_id BIGINT NOT NULL,
    relationship VARCHAR(32) NULL,
    is_primary BOOLEAN NULL,
    bind_date DATE NULL,
    unbind_date DATE NULL,
    status VARCHAR(32) NULL,
    created_at DATETIME(6) NULL,
    updated_at DATETIME(6) NULL,
    deleted_at DATETIME(6) NULL,
    remarks VARCHAR(255) NULL,
    KEY idx_driver_vehicle_driver_id (driver_id),
    KEY idx_driver_vehicle_vehicle_id (vehicle_id),
    KEY idx_driver_vehicle_status (status),
    KEY idx_driver_vehicle_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS offense_type_dict (
    type_id INT PRIMARY KEY AUTO_INCREMENT,
    offense_code VARCHAR(64) NOT NULL,
    offense_name VARCHAR(128) NOT NULL,
    category VARCHAR(64) NULL,
    description VARCHAR(255) NULL,
    standard_fine_amount DECIMAL(12, 2) NULL,
    min_fine_amount DECIMAL(12, 2) NULL,
    max_fine_amount DECIMAL(12, 2) NULL,
    deducted_points INT NULL,
    detention_days INT NULL,
    license_suspension_days INT NULL,
    severity_level VARCHAR(32) NULL,
    legal_basis VARCHAR(255) NULL,
    status VARCHAR(32) NULL,
    created_at DATETIME(6) NULL,
    updated_at DATETIME(6) NULL,
    deleted_at DATETIME(6) NULL,
    remarks VARCHAR(255) NULL,
    UNIQUE KEY uk_offense_type_dict_offense_code (offense_code),
    KEY idx_offense_type_dict_status (status),
    KEY idx_offense_type_dict_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS offense_record (
    offense_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    offense_code VARCHAR(64) NULL,
    offense_number VARCHAR(64) NULL,
    offense_time DATETIME(6) NULL,
    offense_location VARCHAR(255) NULL,
    offense_province VARCHAR(64) NULL,
    offense_city VARCHAR(64) NULL,
    driver_id BIGINT NULL,
    vehicle_id BIGINT NULL,
    offense_description TEXT NULL,
    evidence_type VARCHAR(32) NULL,
    evidence_urls TEXT NULL,
    enforcement_agency VARCHAR(128) NULL,
    enforcement_officer VARCHAR(128) NULL,
    enforcement_device VARCHAR(128) NULL,
    process_status VARCHAR(32) NULL,
    notification_status VARCHAR(32) NULL,
    notification_time DATETIME(6) NULL,
    fine_amount DECIMAL(12, 2) NULL,
    deducted_points INT NULL,
    detention_days INT NULL,
    process_time DATETIME(6) NULL,
    process_handler VARCHAR(128) NULL,
    process_result VARCHAR(255) NULL,
    created_at DATETIME(6) NULL,
    updated_at DATETIME(6) NULL,
    created_by VARCHAR(128) NULL,
    updated_by VARCHAR(128) NULL,
    deleted_at DATETIME(6) NULL,
    remarks VARCHAR(255) NULL,
    UNIQUE KEY uk_offense_record_offense_number (offense_number),
    KEY idx_offense_record_offense_code (offense_code),
    KEY idx_offense_record_driver_id (driver_id),
    KEY idx_offense_record_vehicle_id (vehicle_id),
    KEY idx_offense_record_process_status (process_status),
    KEY idx_offense_record_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fine_record (
    fine_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    offense_id BIGINT NULL,
    fine_number VARCHAR(64) NULL,
    fine_amount DECIMAL(12, 2) NULL,
    late_fee DECIMAL(12, 2) NULL,
    total_amount DECIMAL(12, 2) NULL,
    fine_date DATE NULL,
    payment_deadline DATE NULL,
    issuing_authority VARCHAR(128) NULL,
    handler VARCHAR(128) NULL,
    approver VARCHAR(128) NULL,
    payment_status VARCHAR(32) NULL,
    paid_amount DECIMAL(12, 2) NULL,
    unpaid_amount DECIMAL(12, 2) NULL,
    created_at DATETIME(6) NULL,
    updated_at DATETIME(6) NULL,
    created_by VARCHAR(128) NULL,
    updated_by VARCHAR(128) NULL,
    deleted_at DATETIME(6) NULL,
    remarks VARCHAR(255) NULL,
    UNIQUE KEY uk_fine_record_fine_number (fine_number),
    KEY idx_fine_record_offense_id (offense_id),
    KEY idx_fine_record_payment_status (payment_status),
    KEY idx_fine_record_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payment_record (
    payment_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    fine_id BIGINT NULL,
    payment_number VARCHAR(64) NULL,
    payment_amount DECIMAL(12, 2) NULL,
    payment_method VARCHAR(32) NULL,
    payment_time DATETIME(6) NULL,
    payment_channel VARCHAR(64) NULL,
    payer_name VARCHAR(128) NULL,
    payer_id_card VARCHAR(32) NULL,
    payer_contact VARCHAR(64) NULL,
    bank_name VARCHAR(128) NULL,
    bank_account VARCHAR(128) NULL,
    transaction_id VARCHAR(128) NULL,
    receipt_number VARCHAR(64) NULL,
    receipt_url VARCHAR(512) NULL,
    payment_status VARCHAR(32) NULL,
    refund_amount DECIMAL(12, 2) NULL,
    refund_time DATETIME(6) NULL,
    created_at DATETIME(6) NULL,
    updated_at DATETIME(6) NULL,
    created_by VARCHAR(128) NULL,
    updated_by VARCHAR(128) NULL,
    deleted_at DATETIME(6) NULL,
    remarks VARCHAR(255) NULL,
    UNIQUE KEY uk_payment_record_payment_number (payment_number),
    KEY idx_payment_record_fine_id (fine_id),
    KEY idx_payment_record_status (payment_status),
    KEY idx_payment_record_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS deduction_record (
    deduction_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    offense_id BIGINT NULL,
    driver_id BIGINT NULL,
    deducted_points INT NULL,
    deduction_time DATETIME(6) NULL,
    scoring_cycle VARCHAR(64) NULL,
    handler VARCHAR(128) NULL,
    handler_dept VARCHAR(128) NULL,
    approver VARCHAR(128) NULL,
    approval_time DATETIME(6) NULL,
    status VARCHAR(32) NULL,
    restore_time DATETIME(6) NULL,
    restore_reason VARCHAR(255) NULL,
    created_at DATETIME(6) NULL,
    updated_at DATETIME(6) NULL,
    created_by VARCHAR(128) NULL,
    updated_by VARCHAR(128) NULL,
    deleted_at DATETIME(6) NULL,
    remarks VARCHAR(255) NULL,
    KEY idx_deduction_record_offense_id (offense_id),
    KEY idx_deduction_record_driver_id (driver_id),
    KEY idx_deduction_record_status (status),
    KEY idx_deduction_record_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS appeal_record (
    appeal_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    offense_id BIGINT NULL,
    appeal_number VARCHAR(64) NULL,
    appellant_name VARCHAR(128) NULL,
    appellant_id_card VARCHAR(32) NULL,
    appellant_contact VARCHAR(64) NULL,
    appellant_email VARCHAR(128) NULL,
    appellant_address VARCHAR(255) NULL,
    appeal_type VARCHAR(64) NULL,
    appeal_reason TEXT NULL,
    appeal_time DATETIME(6) NULL,
    evidence_description TEXT NULL,
    evidence_urls TEXT NULL,
    acceptance_status VARCHAR(32) NULL,
    acceptance_time DATETIME(6) NULL,
    acceptance_handler VARCHAR(128) NULL,
    rejection_reason VARCHAR(255) NULL,
    process_status VARCHAR(32) NULL,
    process_time DATETIME(6) NULL,
    process_result VARCHAR(255) NULL,
    process_handler VARCHAR(128) NULL,
    created_at DATETIME(6) NULL,
    updated_at DATETIME(6) NULL,
    created_by VARCHAR(128) NULL,
    updated_by VARCHAR(128) NULL,
    deleted_at DATETIME(6) NULL,
    remarks VARCHAR(255) NULL,
    UNIQUE KEY uk_appeal_record_appeal_number (appeal_number),
    KEY idx_appeal_record_offense_id (offense_id),
    KEY idx_appeal_record_process_status (process_status),
    KEY idx_appeal_record_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS appeal_review (
    review_id BIGINT PRIMARY KEY AUTO_INCREMENT,
    appeal_id BIGINT NULL,
    review_level VARCHAR(32) NULL,
    review_time DATETIME(6) NULL,
    reviewer VARCHAR(128) NULL,
    reviewer_dept VARCHAR(128) NULL,
    review_result VARCHAR(32) NULL,
    review_opinion TEXT NULL,
    suggested_action VARCHAR(64) NULL,
    suggested_fine_amount DECIMAL(12, 2) NULL,
    suggested_points INT NULL,
    created_at DATETIME(6) NULL,
    updated_at DATETIME(6) NULL,
    deleted_at DATETIME(6) NULL,
    remarks VARCHAR(255) NULL,
    KEY idx_appeal_review_appeal_id (appeal_id),
    KEY idx_appeal_review_review_result (review_result),
    KEY idx_appeal_review_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
