ALTER TABLE sys_user
    ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS organization_code VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS region_code VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS department_code VARCHAR(64) NULL;

ALTER TABLE sys_request_history
    ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS organization_code VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS region_code VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS department_code VARCHAR(64) NULL;

ALTER TABLE sys_backup_restore
    ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS organization_code VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS region_code VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS department_code VARCHAR(64) NULL;

ALTER TABLE audit_login_log
    ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS organization_code VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS region_code VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS department_code VARCHAR(64) NULL;

ALTER TABLE audit_operation_log
    ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS organization_code VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS region_code VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS department_code VARCHAR(64) NULL;

ALTER TABLE driver_information
    ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS organization_code VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS region_code VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS department_code VARCHAR(64) NULL;

ALTER TABLE vehicle_information
    ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS organization_code VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS region_code VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS department_code VARCHAR(64) NULL;

ALTER TABLE driver_vehicle
    ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS organization_code VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS region_code VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS department_code VARCHAR(64) NULL;

ALTER TABLE offense_record
    ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS organization_code VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS region_code VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS department_code VARCHAR(64) NULL;

ALTER TABLE fine_record
    ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS organization_code VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS region_code VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS department_code VARCHAR(64) NULL;

ALTER TABLE payment_record
    ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS organization_code VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS region_code VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS department_code VARCHAR(64) NULL;

ALTER TABLE deduction_record
    ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS organization_code VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS region_code VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS department_code VARCHAR(64) NULL;

ALTER TABLE appeal_record
    ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS organization_code VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS region_code VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS department_code VARCHAR(64) NULL;

ALTER TABLE appeal_review
    ADD COLUMN IF NOT EXISTS tenant_id VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS organization_code VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS region_code VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS department_code VARCHAR(64) NULL;
